export {default as Header} from './Header/Header'
export {default as Settings} from './Settings/Settings'
export {default as Landing} from './Landing/Landing'
export {default as Container} from './Container/Container'
export {default as Footer} from './Footer/Footer'